---
AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Aurora Global database primary region Mysql

Parameters:

  VPCId:
    Type: String
  InstanceType:
    Default: db.r6g.large
    Type: String
    AllowedValues:
      - db.r6g.large
      - db.r6g.2xlarge
  DatabaseName:
    Default: gdbdatabase
    Type: String
  SubnetGroup:
    Type: String  
  MinorVersionUpgrade:
    Default: 'No'
    Type: String
    AllowedValues:
      - 'Yes'
      - 'No'
  EngineVersion:
    Default: '8.0.mysql_aurora.3.03.2'
    Type: String
    AllowedValues:
      - "8.0.mysql_aurora.3.02.0"
      - "8.0.mysql_aurora.3.02.1"
      - "8.0.mysql_aurora.3.02.2"
      - "8.0.mysql_aurora.3.02.3"
      - "8.0.mysql_aurora.3.03.0"
      - "8.0.mysql_aurora.3.03.1"
      - "8.0.mysql_aurora.3.03.2"
      - "8.0.mysql_aurora.3.04.0"
  MysqlEngineMode:
    Default: 'provisioned'
    Type: String
    AllowedValues:
      - 'global'
      - 'provisioned'
  ClusterName:
    Default: aurora-cluster-serverless
    Type: String
  GlobalClusterIdentifier:
    Default: aurora-global-cluster
    Type: String

Resources:

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VPCId
      GroupDescription: Access to database
      SecurityGroupIngress:
        - ToPort: 3306
          FromPort: 3306
          IpProtocol: tcp
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub ${DatabaseName}-security-group

  DBCluster:
    DependsOn:  SecurityGroup 
    Type: AWS::RDS::DBCluster
    Properties:
      DBClusterIdentifier: !Ref ClusterName
      DBSubnetGroupName: !Ref SubnetGroup
      GlobalClusterIdentifier: !Ref GlobalClusterIdentifier
      ServerlessV2ScalingConfiguration:
        MinCapacity: 0.5
        MaxCapacity: 2
      DeletionProtection: false
      Engine: aurora-mysql
      EngineVersion: !Ref EngineVersion
      SourceRegion: us-west-2
      Port: 3306
      StorageEncrypted: false
      VpcSecurityGroupIds:
        - !Ref SecurityGroup

  DBInstance1:
    DependsOn: DBCluster 
    Type: AWS::RDS::DBInstance
    Properties:
      AllowMajorVersionUpgrade: false
      AutoMinorVersionUpgrade: True
      DBClusterIdentifier: !Ref DBCluster
      DBInstanceIdentifier: !Sub '${ClusterName}-serverless'
      DBInstanceClass: db.serverless
      EngineMode: serverless
      DBSubnetGroupName: !Ref SubnetGroup
      Engine: aurora-mysql
      EngineVersion: !Ref EngineVersion
      PubliclyAccessible: false


Outputs:
  DBEndpoint:
    Value: !GetAtt DBCluster.Endpoint.Address
  DBPort:
    Value: !GetAtt DBCluster.Endpoint.Port